version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  # pgAdmin (GUI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_network

  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  # phpMyAdmin (GUI for MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - 8080:80
    networks:
      - db_network

# Volumes for persistent storage
volumes:
  postgres_data:
  pgadmin_data:
  mysql_data:

# Network for communication between services
networks:
  db_network: