version: "3.8"

services:
  # Kafka and Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PySpark
  pyspark:
    image: bitnami/spark:latest
    container_name: pyspark
    ports:
      - "4040:4040"  # Spark UI
    volumes:
      - ./scripts:/app  # Mount local scripts directory
    environment:
      - SPARK_MODE=master
    depends_on:
      - postgres

  # Apache Superset
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "your_secret_key"
      SUPERSET_LOAD_EXAMPLES: "no"
    volumes:
      - superset_data:/app/superset_home
    depends_on:
      - postgres

# Volumes for persistent storage
volumes:
  postgres_data:
  superset_data:

# Network for communication
networks:
  default:
    name: data_pipeline_network